In [1]:
import pandas as pd
import numpy as np
import datetime

In [2]:
df = pd.read_excel('http://www.leb.esalq.usp.br/leb/automatica/diario2020.xls')
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 24)

In [3]:
columns = df.iloc[6].tolist()

In [4]:
df_data = df.iloc[9:]
df_data.columns = columns
df_data.head(10)

,TIMESTAMP,RECORD,BattV_Avg,Tar_AVG,UR_inst,Vvento_ms_AVG,Dvento_G,Qg_AVG,PAR_AVG,Rn_Avg,Chuva_mm,Patm_kPa_AVG,rQg_AVG,Qatm_AVG,Qsup_AVG,Boc_AVG,Bol_AVG,Albedo_Avg,QatmC_AVG,QsupC_AVG,Vvento_ms_S_WVT,Dvento_D1_WVT,Dvento_SD1_WVT,PainelT
9,2020-01-01 00:00:00,8754,12.46,24.78,79.76,0.79,72.16,0,0,-27.97,0,94.6,0,0,0,0,0,0,0,0,0.79,72.16,24.79,24.61
10,2020-01-01 00:15:00,8755,12.46,24.34,80.9,0.515,183.6,0,0,-34.07,0,94.6,0,0,0,0,0,0,0,0,0.515,169.9,50.78,24.52
11,2020-01-01 00:30:00,8756,12.45,24.28,82.2,0.883,68.63,0,0,-35.25,0,94.6,0,0,0,0,0,0,0,0,0.883,68.63,23.03,24.35
12,2020-01-01 00:45:00,8757,12.45,24.05,84.2,0.767,77.47,0,0,-35.51,0,94.5,0,0,0,0,0,0,0,0,0.767,77.47,19.52,24.19
13,2020-01-01 01:00:00,8758,12.44,23.49,88.2,0.348,41.53,0,0,-35.61,0,94.5,0,0,0,0,0,0,0,0,0.348,51.07,9.48,24
14,2020-01-01 01:15:00,8759,12.44,23.11,89,0,33.06,0,0,-33.75,0,94.5,0,0,0,0,0,0,0,0,0,0,0,23.74
15,2020-01-01 01:30:00,8760,12.43,22.93,89.3,0.005,343.3,0,0,-32.99,0,94.5,0,0,0,0,0,0,0,0,0.005,277.4,0,23.44
16,2020-01-01 01:45:00,8761,12.43,22.97,86.2,0.367,266,0,0,-35.38,0,94.5,0,0,0,0,0,0,0,0,0.367,297,14,23.2
17,2020-01-01 02:00:00,8762,12.42,23.03,86.7,0.679,243.2,0,0,-32.73,0,94.5,0,0,0,0,0,0,0,0,0.679,251,68.71,23.06
18,2020-01-01 02:15:00,8763,12.42,23.02,86.2,0.452,20.56,0,0,-33.49,0,94.5,0,0,0,0,0,0,0,0,0.452,36.55,15.05,22.92

In [5]:
df_data['TIMESTAMP'] = pd.to_datetime(df_data['TIMESTAMP'])
df_data.head()

<ipython-input-5-070f5a0eac02>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_data['TIMESTAMP'] = pd.to_datetime(df_data['TIMESTAMP'])

,TIMESTAMP,RECORD,BattV_Avg,Tar_AVG,UR_inst,Vvento_ms_AVG,Dvento_G,Qg_AVG,PAR_AVG,Rn_Avg,Chuva_mm,Patm_kPa_AVG,rQg_AVG,Qatm_AVG,Qsup_AVG,Boc_AVG,Bol_AVG,Albedo_Avg,QatmC_AVG,QsupC_AVG,Vvento_ms_S_WVT,Dvento_D1_WVT,Dvento_SD1_WVT,PainelT
9,2020-01-01 00:00:00,8754,12.46,24.78,79.76,0.79,72.16,0,0,-27.97,0,94.6,0,0,0,0,0,0,0,0,0.79,72.16,24.79,24.61
10,2020-01-01 00:15:00,8755,12.46,24.34,80.9,0.515,183.6,0,0,-34.07,0,94.6,0,0,0,0,0,0,0,0,0.515,169.9,50.78,24.52
11,2020-01-01 00:30:00,8756,12.45,24.28,82.2,0.883,68.63,0,0,-35.25,0,94.6,0,0,0,0,0,0,0,0,0.883,68.63,23.03,24.35
12,2020-01-01 00:45:00,8757,12.45,24.05,84.2,0.767,77.47,0,0,-35.51,0,94.5,0,0,0,0,0,0,0,0,0.767,77.47,19.52,24.19
13,2020-01-01 01:00:00,8758,12.44,23.49,88.2,0.348,41.53,0,0,-35.61,0,94.5,0,0,0,0,0,0,0,0,0.348,51.07,9.48,24

In [6]:
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35148 entries, 9 to 35156
Data columns (total 24 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TIMESTAMP        35148 non-null  datetime64[ns]
 1   RECORD           34912 non-null  object
 2   BattV_Avg        34912 non-null  object
 3   Tar_AVG          35067 non-null  object
 4   UR_inst          35067 non-null  object
 5   Vvento_ms_AVG    34912 non-null  object
 6   Dvento_G         34912 non-null  object
 7   Qg_AVG           34912 non-null  object
 8   PAR_AVG          34912 non-null  object
 9   Rn_Avg           34912 non-null  object
 10  Chuva_mm         34912 non-null  object
 11  Patm_kPa_AVG     34912 non-null  object
 12  rQg_AVG          34912 non-null  object
 13  Qatm_AVG         34912 non-null  object
 14  Qsup_AVG         34912 non-null  object
 15  Boc_AVG          34912 non-null  object
 16  Bol_AVG          34912 non-null  object
 17  Albedo_Avg       34912 non-null  object
 18  QatmC_AVG        34912 non-null  object
 19  QsupC_AVG        34912 non-null  object
 20  Vvento_ms_S_WVT  34912 non-null  object
 21  Dvento_D1_WVT    34912 non-null  object
 22  Dvento_SD1_WVT   34912 non-null  object
 23  PainelT          34912 non-null  object
dtypes: datetime64[ns](1), object(23)
memory usage: 6.4+ MB

In [7]:
df_data[df_data['Chuva_mm'].notnull()].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34912 entries, 9 to 35156
Data columns (total 24 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TIMESTAMP        34912 non-null  datetime64[ns]
 1   RECORD           34912 non-null  object
 2   BattV_Avg        34912 non-null  object
 3   Tar_AVG          34912 non-null  object
 4   UR_inst          34912 non-null  object
 5   Vvento_ms_AVG    34912 non-null  object
 6   Dvento_G         34912 non-null  object
 7   Qg_AVG           34912 non-null  object
 8   PAR_AVG          34912 non-null  object
 9   Rn_Avg           34912 non-null  object
 10  Chuva_mm         34912 non-null  object
 11  Patm_kPa_AVG     34912 non-null  object
 12  rQg_AVG          34912 non-null  object
 13  Qatm_AVG         34912 non-null  object
 14  Qsup_AVG         34912 non-null  object
 15  Boc_AVG          34912 non-null  object
 16  Bol_AVG          34912 non-null  object
 17  Albedo_Avg       34912 non-null  object
 18  QatmC_AVG        34912 non-null  object
 19  QsupC_AVG        34912 non-null  object
 20  Vvento_ms_S_WVT  34912 non-null  object
 21  Dvento_D1_WVT    34912 non-null  object
 22  Dvento_SD1_WVT   34912 non-null  object
 23  PainelT          34912 non-null  object
dtypes: datetime64[ns](1), object(23)
memory usage: 6.7+ MB

Apenas retirando os dados sem chuva, temos o dataset limpo. __É PRECISO CONFIRMAR SE ESSE COMPORTAMENTO SE REFLETE COM O RESTO DOS DADOS__.

In [8]:
firstYear = 1997
currYear = datetime.date.today().year

url = 'http://www.leb.esalq.usp.br/leb/automatica/diario{year}.xls'

for year in range(firstYear, currYear + 1):
    data_raw = pd.read_excel(url.format(year=year))
    index_columns = 0
    
    # Verifying correct columns and values for each year
    if year < 2003:
        index_columns = 11
    elif year < 2017:
        index_columns = 14
    else:
        index_columns = 6
    
    columns_data = data_raw.iloc[index_columns].tolist()
    data_nan_columns = data_raw.iloc[index_columns + 3:].copy()
    
    # Transform different target names to a unique name and remove NaN column names
    columns_data = ['Chuva' if column == 'Chuva_mm' or column == 'Precip' else column for column in columns_data]
    columns_notna = [column for column in columns_data if column is not np.nan]
    
    data_nan_columns.columns = columns_data
    
    # Add valid columns to new dataframe
    data_nan_columns = data_nan_columns[data_nan_columns['Chuva'].notnull()]
    
    data_valid_columns = data_nan_columns[columns_notna].copy()
    
    # Verifying null values in columns after cleaning target values
    print(f'{year}: \n\nColunas padrão: {columns_notna}')
    print(f'Colunas não nulas: {columns_notna}')
    
    if data_valid_columns.isnull().values.any():
        print('Resultado: Valor nulo detectado após limpeza em ', end='')
        
        columns_null = []
        for column in columns_notna:
            if data_valid_columns[column].isnull().values.any():
                columns_null.append(column)
                
        print(columns_null)
    else:
        print('Resultado: OK')
        
    print('\n---------------------------------------------------------------\n')

1997:

Colunas padrão: ['Dia Juliano', 'Horario', 'Tar', 'UR', 'Vento', 'Vento', 'Rad.Solar', 'PAR', 'Rad.Liq.', 'Niv Tanq', 'Chuva']
Colunas não nulas: ['Dia Juliano', 'Horario', 'Tar', 'UR', 'Vento', 'Vento', 'Rad.Solar', 'PAR', 'Rad.Liq.', 'Niv Tanq', 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['Dia Juliano', 'Horario', 'Tar', 'Vento', 'Vento', 'Rad.Solar', 'PAR', 'Rad.Liq.', 'Niv Tanq']

---------------------------------------------------------------

1998:

Colunas padrão: ['Dia Juliano', 'Horario', 'Tar', 'UR', 'Vento', 'Vento', 'Rad.Solar', 'PAR', 'Rad.Liq.', 'Niv Tanq', 'Chuva']
Colunas não nulas: ['Dia Juliano', 'Horario', 'Tar', 'UR', 'Vento', 'Vento', 'Rad.Solar', 'PAR', 'Rad.Liq.', 'Niv Tanq', 'Chuva']
Resultado: OK

---------------------------------------------------------------

1999:

Colunas padrão: ['Dia Juliano', 'Horario', 'Tar', 'UR', 'Vento', 'Vento', 'Rad.Solar', 'PAR', 'Rad.Liq.', 'Niv Tanq', 'Chuva']
Colunas não nulas: ['Dia Juliano', 'Horario', 'Tar', 'UR', 'Vento', 'Vento', 'Rad.Solar', 'PAR', 'Rad.Liq.', 'Niv Tanq', 'Chuva']
Resultado: OK

---------------------------------------------------------------

2000:

Colunas padrão: ['Dia Juliano', 'Horário', 'Tar', 'Vento', 'Vento', 'Rad.Solar', 'PAR', 'RS EPP', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Chuva']
Colunas não nulas: ['Dia Juliano', 'Horário', 'Tar', 'Vento', 'Vento', 'Rad.Solar', 'PAR', 'RS EPP', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['RS EPP', ' es', ' ea', 'Tu', 'To', '  DPV']

---------------------------------------------------------------

2001:

Colunas padrão: ['Dia Juliano', 'Horário', 'Tar', 'Vento', 'Vento', 'Rad.Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Eppley', 'Chuva']
Colunas não nulas: ['Dia Juliano', 'Horário', 'Tar', 'Vento', 'Vento', 'Rad.Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Eppley', 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['Niv Tanq', 'Eppley']

---------------------------------------------------------------

2002:

Colunas padrão: ['Dia Juliano', 'Horário', 'Tar', 'Vento', 'Vento', 'Rad.Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Eppley', 'Chuva']
Colunas não nulas: ['Dia Juliano', 'Horário', 'Tar', 'Vento', 'Vento', 'Rad.Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Eppley', 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['F.C.S.', 'Eppley']

---------------------------------------------------------------

2003:

Colunas padrão: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Colunas não nulas: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['Desv. Pad.', 'F.C.S.', 'Niv Tanq', 'Rad Epp']

---------------------------------------------------------------

2004:

Colunas padrão: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Colunas não nulas: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['F.C.S.', 'To', 'Niv Tanq', 'Rad Epp']

---------------------------------------------------------------

2005:

Colunas padrão: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Colunas não nulas: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['F.C.S.', 'Niv Tanq', 'Rad Epp']

---------------------------------------------------------------

2006:

Colunas padrão: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Colunas não nulas: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['F.C.S.', 'Niv Tanq', 'Rad Epp']

---------------------------------------------------------------

2007:

Colunas padrão: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Colunas não nulas: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['F.C.S.', 'Niv Tanq', 'Rad Epp']

---------------------------------------------------------------

2008:

Colunas padrão: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Colunas não nulas: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['F.C.S.', 'Niv Tanq', 'Rad Epp']

---------------------------------------------------------------

2009:

Colunas padrão: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', nan, 'Chuva']
Colunas não nulas: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', nan, 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['F.C.S.', 'Tu', 'Niv Tanq', nan]

---------------------------------------------------------------

2010:

Colunas padrão: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', nan, 'Chuva']
Colunas não nulas: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', nan, 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['F.C.S.', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', nan]

---------------------------------------------------------------

2011:

Colunas padrão: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Colunas não nulas: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['F.C.S.', 'Tu', 'To', 'Niv Tanq', 'Rad Epp']

---------------------------------------------------------------

2012:

Colunas padrão: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Colunas não nulas: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['F.C.S.', ' ea', 'Tu', 'To', 'UR', 'Niv Tanq', 'Rad Epp']

---------------------------------------------------------------

2013:

Colunas padrão: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Colunas não nulas: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['F.C.S.', 'Tu', 'To', 'Niv Tanq', 'Rad Epp']

---------------------------------------------------------------

2014:

Colunas padrão: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva', nan]
Colunas não nulas: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva', nan]
Resultado: Valor nulo detectado após limpeza em ['F.C.S.', 'Tu', 'Rad Epp', nan]

---------------------------------------------------------------

2015:

Colunas padrão: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Colunas não nulas: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['F.C.S.', 'Tu', 'Rad Epp']

---------------------------------------------------------------

2016:

Colunas padrão: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Colunas não nulas: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['Dia', 'Horas', 'F.C.S.', 'Tu', 'Rad Epp']

---------------------------------------------------------------

2017:

Colunas padrão: ['TIMESTAMP', 'RECORD', 'BattV_Avg', 'Tar_AVG', 'UR_inst', 'Vvento_ms_AVG', 'Dvento_G', 'Qg_AVG', 'PAR_AVG', 'Rn_Avg', 'Chuva', 'Patm_kPa_AVG', 'rQg_AVG', 'Qatm_AVG', 'Qsup_AVG', 'Boc_AVG', 'Bol_AVG', 'Albedo_Avg', 'QatmC_AVG', 'QsupC_AVG', 'Vvento_ms_S_WVT', 'Dvento_D1_WVT', 'Dvento_SD1_WVT', 'PainelT']
Colunas não nulas: ['TIMESTAMP', 'RECORD', 'BattV_Avg', 'Tar_AVG', 'UR_inst', 'Vvento_ms_AVG', 'Dvento_G', 'Qg_AVG', 'PAR_AVG', 'Rn_Avg', 'Chuva', 'Patm_kPa_AVG', 'rQg_AVG', 'Qatm_AVG', 'Qsup_AVG', 'Boc_AVG', 'Bol_AVG', 'Albedo_Avg', 'QatmC_AVG', 'QsupC_AVG', 'Vvento_ms_S_WVT', 'Dvento_D1_WVT', 'Dvento_SD1_WVT', 'PainelT']
Resultado: OK

---------------------------------------------------------------

2018:

Colunas padrão: ['TIMESTAMP', 'RECORD', 'BattV_Avg', 'Tar_AVG', 'UR_inst', 'Vvento_ms_AVG', 'Dvento_G', 'Qg_AVG', 'PAR_AVG', 'Rn_Avg', 'Chuva', 'Patm_kPa_AVG', 'rQg_AVG', 'Qatm_AVG', 'Qsup_AVG', 'Boc_AVG', 'Bol_AVG', 'Albedo_Avg', 'QatmC_AVG', 'QsupC_AVG', 'Vvento_ms_S_WVT', 'Dvento_D1_WVT', 'Dvento_SD1_WVT', 'PainelT']
Colunas não nulas: ['TIMESTAMP', 'RECORD', 'BattV_Avg', 'Tar_AVG', 'UR_inst', 'Vvento_ms_AVG', 'Dvento_G', 'Qg_AVG', 'PAR_AVG', 'Rn_Avg', 'Chuva', 'Patm_kPa_AVG', 'rQg_AVG', 'Qatm_AVG', 'Qsup_AVG', 'Boc_AVG', 'Bol_AVG', 'Albedo_Avg', 'QatmC_AVG', 'QsupC_AVG', 'Vvento_ms_S_WVT', 'Dvento_D1_WVT', 'Dvento_SD1_WVT', 'PainelT']
Resultado: OK

---------------------------------------------------------------

2019:

Colunas padrão: ['TIMESTAMP', 'RECORD', 'BattV_Avg', 'Tar_AVG', 'UR_inst', 'Vvento_ms_AVG', 'Dvento_G', 'Qg_AVG', 'PAR_AVG', 'Rn_Avg', 'Chuva', 'Patm_kPa_AVG', 'rQg_AVG', 'Qatm_AVG', 'Qsup_AVG', 'Boc_AVG', 'Bol_AVG', 'Albedo_Avg', 'QatmC_AVG', 'QsupC_AVG', 'Vvento_ms_S_WVT', 'Dvento_D1_WVT', 'Dvento_SD1_WVT', 'PainelT']
Colunas não nulas: ['TIMESTAMP', 'RECORD', 'BattV_Avg', 'Tar_AVG', 'UR_inst', 'Vvento_ms_AVG', 'Dvento_G', 'Qg_AVG', 'PAR_AVG', 'Rn_Avg', 'Chuva', 'Patm_kPa_AVG', 'rQg_AVG', 'Qatm_AVG', 'Qsup_AVG', 'Boc_AVG', 'Bol_AVG', 'Albedo_Avg', 'QatmC_AVG', 'QsupC_AVG', 'Vvento_ms_S_WVT', 'Dvento_D1_WVT', 'Dvento_SD1_WVT', 'PainelT']
Resultado: Valor nulo detectado após limpeza em ['RECORD', 'BattV_Avg', 'Dvento_G', 'PAR_AVG', 'Rn_Avg', 'Patm_kPa_AVG', 'rQg_AVG', 'Qatm_AVG', 'Qsup_AVG', 'Boc_AVG', 'Bol_AVG', 'Albedo_Avg', 'QatmC_AVG', 'QsupC_AVG', 'Vvento_ms_S_WVT', 'Dvento_D1_WVT', 'Dvento_SD1_WVT', 'PainelT']

---------------------------------------------------------------

2020:

Colunas padrão: ['TIMESTAMP', 'RECORD', 'BattV_Avg', 'Tar_AVG', 'UR_inst', 'Vvento_ms_AVG', 'Dvento_G', 'Qg_AVG', 'PAR_AVG', 'Rn_Avg', 'Chuva', 'Patm_kPa_AVG', 'rQg_AVG', 'Qatm_AVG', 'Qsup_AVG', 'Boc_AVG', 'Bol_AVG', 'Albedo_Avg', 'QatmC_AVG', 'QsupC_AVG', 'Vvento_ms_S_WVT', 'Dvento_D1_WVT', 'Dvento_SD1_WVT', 'PainelT']
Colunas não nulas: ['TIMESTAMP', 'RECORD', 'BattV_Avg', 'Tar_AVG', 'UR_inst', 'Vvento_ms_AVG', 'Dvento_G', 'Qg_AVG', 'PAR_AVG', 'Rn_Avg', 'Chuva', 'Patm_kPa_AVG', 'rQg_AVG', 'Qatm_AVG', 'Qsup_AVG', 'Boc_AVG', 'Bol_AVG', 'Albedo_Avg', 'QatmC_AVG', 'QsupC_AVG', 'Vvento_ms_S_WVT', 'Dvento_D1_WVT', 'Dvento_SD1_WVT', 'PainelT']
Resultado: OK

---------------------------------------------------------------

2021:

Colunas padrão: ['TIMESTAMP', 'RECORD', 'BattV_Avg', 'Tar_AVG', 'UR_inst', 'Vvento_ms_AVG', 'Dvento_G', 'Qg_AVG', 'PAR_AVG', 'Rn_Avg', 'Chuva', 'Patm_kPa_AVG', 'rQg_AVG', 'Qatm_AVG', 'Qsup_AVG', 'Boc_AVG', 'Bol_AVG', 'Albedo_Avg', 'QatmC_AVG', 'QsupC_AVG', 'Vvento_ms_S_WVT', 'Dvento_D1_WVT', 'Dvento_SD1_WVT', 'PainelT']
Colunas não nulas: ['TIMESTAMP', 'RECORD', 'BattV_Avg', 'Tar_AVG', 'UR_inst', 'Vvento_ms_AVG', 'Dvento_G', 'Qg_AVG', 'PAR_AVG', 'Rn_Avg', 'Chuva', 'Patm_kPa_AVG', 'rQg_AVG', 'Qatm_AVG', 'Qsup_AVG', 'Boc_AVG', 'Bol_AVG', 'Albedo_Avg', 'QatmC_AVG', 'QsupC_AVG', 'Vvento_ms_S_WVT', 'Dvento_D1_WVT', 'Dvento_SD1_WVT', 'PainelT']
Resultado: OK

---------------------------------------------------------------

In [9]:
firstYear = 1997
currYear = datetime.date.today().year

url = 'http://www.leb.esalq.usp.br/leb/automatica/diario{year}.xls'

for year in range(firstYear, currYear + 1):
    data_raw = pd.read_excel(url.format(year=year))
    index_columns = 0
    
    # Verifying correct columns and values for each year
    if year < 2003:
        index_columns = 11
    elif year < 2017:
        index_columns = 14
    else:
        index_columns = 6
    
    columns_data = data_raw.iloc[index_columns].tolist()
    data_nan_columns = data_raw.iloc[index_columns + 3:].copy()
    
    # Transform different target names to a unique name and remove NaN column names
    columns_data = ['Chuva' if column == 'Chuva_mm' or column == 'Precip' else column for column in columns_data]
    columns_notna = [column for column in columns_data if column is not np.nan]
    
    data_nan_columns.columns = columns_data
    
    # Add valid columns to new dataframe
    data_nan_columns = data_nan_columns[data_nan_columns['Chuva'].notnull()]
    
    data_valid_columns = data_nan_columns[columns_notna].copy()
    
    # Verifying null values in columns after cleaning target values
    print(f'{year}: \n\nColunas padrão: {columns_data}')
    print(f'Colunas não nulas: {columns_notna}')
    
    if data_valid_columns.isnull().values.any():
        print('Resultado: Valor nulo detectado após limpeza em ', end='')
        
        columns_null = []
        for column in columns_notna:
            if data_valid_columns[column].isnull().values.any():
                data_valid_columns = data_valid_columns[data_valid_columns[column].notnull()]
                columns_null.append(column)
                
        print(columns_null)
        print(f'Registros após remoções: {data_valid_columns.shape[0]} linhas')
    else:
        print('Resultado: OK')
        
    print('\n---------------------------------------------------------------\n')

1997:

Colunas padrão: ['Dia Juliano', 'Horario', 'Tar', 'UR', 'Vento', 'Vento', 'Rad.Solar', 'PAR', 'Rad.Liq.', 'Niv Tanq', 'Chuva']
Colunas não nulas: ['Dia Juliano', 'Horario', 'Tar', 'UR', 'Vento', 'Vento', 'Rad.Solar', 'PAR', 'Rad.Liq.', 'Niv Tanq', 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['Dia Juliano', 'Niv Tanq']
Registros após remoções: 5430 linhas

---------------------------------------------------------------

1998:

Colunas padrão: ['Dia Juliano', 'Horario', 'Tar', 'UR', 'Vento', 'Vento', 'Rad.Solar', 'PAR', 'Rad.Liq.', 'Niv Tanq', 'Chuva']
Colunas não nulas: ['Dia Juliano', 'Horario', 'Tar', 'UR', 'Vento', 'Vento', 'Rad.Solar', 'PAR', 'Rad.Liq.', 'Niv Tanq', 'Chuva']
Resultado: OK

---------------------------------------------------------------

1999:

Colunas padrão: ['Dia Juliano', 'Horario', 'Tar', 'UR', 'Vento', 'Vento', 'Rad.Solar', 'PAR', 'Rad.Liq.', 'Niv Tanq', 'Chuva']
Colunas não nulas: ['Dia Juliano', 'Horario', 'Tar', 'UR', 'Vento', 'Vento', 'Rad.Solar', 'PAR', 'Rad.Liq.', 'Niv Tanq', 'Chuva']
Resultado: OK

---------------------------------------------------------------

2000:

Colunas padrão: ['Dia Juliano', 'Horário', 'Tar', 'Vento', 'Vento', 'Rad.Solar', 'PAR', 'RS EPP', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Chuva']
Colunas não nulas: ['Dia Juliano', 'Horário', 'Tar', 'Vento', 'Vento', 'Rad.Solar', 'PAR', 'RS EPP', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['RS EPP']
Registros após remoções: 24030 linhas

---------------------------------------------------------------

2001:

Colunas padrão: ['Dia Juliano', 'Horário', 'Tar', 'Vento', 'Vento', 'Rad.Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Eppley', 'Chuva']
Colunas não nulas: ['Dia Juliano', 'Horário', 'Tar', 'Vento', 'Vento', 'Rad.Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Eppley', 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['Niv Tanq', 'Eppley']
Registros após remoções: 0 linhas

---------------------------------------------------------------

2002:

Colunas padrão: ['Dia Juliano', 'Horário', 'Tar', 'Vento', 'Vento', 'Rad.Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Eppley', 'Chuva']
Colunas não nulas: ['Dia Juliano', 'Horário', 'Tar', 'Vento', 'Vento', 'Rad.Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Eppley', 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['F.C.S.', 'Eppley']
Registros após remoções: 0 linhas

---------------------------------------------------------------

2003:

Colunas padrão: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Colunas não nulas: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['Desv. Pad.', 'F.C.S.']
Registros após remoções: 0 linhas

---------------------------------------------------------------

2004:

Colunas padrão: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Colunas não nulas: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['F.C.S.']
Registros após remoções: 0 linhas

---------------------------------------------------------------

2005:

Colunas padrão: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Colunas não nulas: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['F.C.S.']
Registros após remoções: 0 linhas

---------------------------------------------------------------

2006:

Colunas padrão: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Colunas não nulas: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['F.C.S.', 'Rad Epp']
Registros após remoções: 1 linhas

---------------------------------------------------------------

2007:

Colunas padrão: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Colunas não nulas: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['F.C.S.']
Registros após remoções: 0 linhas

---------------------------------------------------------------

2008:

Colunas padrão: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva', nan]
Colunas não nulas: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['F.C.S.', 'Rad Epp']
Registros após remoções: 0 linhas

---------------------------------------------------------------

2009:

Colunas padrão: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', nan, 'Chuva']
Colunas não nulas: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', nan, 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['F.C.S.']
Registros após remoções: 0 linhas

---------------------------------------------------------------

2010:

Colunas padrão: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', nan, 'Chuva', nan]
Colunas não nulas: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', nan, 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['F.C.S.']
Registros após remoções: 0 linhas

---------------------------------------------------------------

2011:

Colunas padrão: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva', nan]
Colunas não nulas: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['F.C.S.']
Registros após remoções: 0 linhas

---------------------------------------------------------------

2012:

Colunas padrão: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva', nan]
Colunas não nulas: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['F.C.S.']
Registros após remoções: 0 linhas

---------------------------------------------------------------

2013:

Colunas padrão: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva', nan]
Colunas não nulas: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['F.C.S.']
Registros após remoções: 0 linhas

---------------------------------------------------------------

2014:

Colunas padrão: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva', nan]
Colunas não nulas: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva', nan]
Resultado: Valor nulo detectado após limpeza em ['F.C.S.']
Registros após remoções: 0 linhas

---------------------------------------------------------------

2015:

Colunas padrão: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva', nan]
Colunas não nulas: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['F.C.S.']
Registros após remoções: 0 linhas

---------------------------------------------------------------

2016:

Colunas padrão: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva', nan, nan, nan, nan, nan]
Colunas não nulas: ['Dia', 'Horas', 'Tar', 'Vento', 'Dir Ven', 'Desv. Pad.', 'Rad. Solar', 'PAR', 'F.C.S.', 'Rad.Liq.', ' es', ' ea', 'Tu', 'To', 'UR', '  DPV', 'Niv Tanq', 'Rad Epp', 'Chuva']
Resultado: Valor nulo detectado após limpeza em ['Dia', 'F.C.S.', 'Rad Epp']
Registros após remoções: 25931 linhas

---------------------------------------------------------------

2017:

Colunas padrão: ['TIMESTAMP', 'RECORD', 'BattV_Avg', 'Tar_AVG', 'UR_inst', 'Vvento_ms_AVG', 'Dvento_G', 'Qg_AVG', 'PAR_AVG', 'Rn_Avg', 'Chuva', 'Patm_kPa_AVG', 'rQg_AVG', 'Qatm_AVG', 'Qsup_AVG', 'Boc_AVG', 'Bol_AVG', 'Albedo_Avg', 'QatmC_AVG', 'QsupC_AVG', 'Vvento_ms_S_WVT', 'Dvento_D1_WVT', 'Dvento_SD1_WVT', 'PainelT']
Colunas não nulas: ['TIMESTAMP', 'RECORD', 'BattV_Avg', 'Tar_AVG', 'UR_inst', 'Vvento_ms_AVG', 'Dvento_G', 'Qg_AVG', 'PAR_AVG', 'Rn_Avg', 'Chuva', 'Patm_kPa_AVG', 'rQg_AVG', 'Qatm_AVG', 'Qsup_AVG', 'Boc_AVG', 'Bol_AVG', 'Albedo_Avg', 'QatmC_AVG', 'QsupC_AVG', 'Vvento_ms_S_WVT', 'Dvento_D1_WVT', 'Dvento_SD1_WVT', 'PainelT']
Resultado: OK

---------------------------------------------------------------

2018:

Colunas padrão: ['TIMESTAMP', 'RECORD', 'BattV_Avg', 'Tar_AVG', 'UR_inst', 'Vvento_ms_AVG', 'Dvento_G', 'Qg_AVG', 'PAR_AVG', 'Rn_Avg', 'Chuva', 'Patm_kPa_AVG', 'rQg_AVG', 'Qatm_AVG', 'Qsup_AVG', 'Boc_AVG', 'Bol_AVG', 'Albedo_Avg', 'QatmC_AVG', 'QsupC_AVG', 'Vvento_ms_S_WVT', 'Dvento_D1_WVT', 'Dvento_SD1_WVT', 'PainelT']
Colunas não nulas: ['TIMESTAMP', 'RECORD', 'BattV_Avg', 'Tar_AVG', 'UR_inst', 'Vvento_ms_AVG', 'Dvento_G', 'Qg_AVG', 'PAR_AVG', 'Rn_Avg', 'Chuva', 'Patm_kPa_AVG', 'rQg_AVG', 'Qatm_AVG', 'Qsup_AVG', 'Boc_AVG', 'Bol_AVG', 'Albedo_Avg', 'QatmC_AVG', 'QsupC_AVG', 'Vvento_ms_S_WVT', 'Dvento_D1_WVT', 'Dvento_SD1_WVT', 'PainelT']
Resultado: OK

---------------------------------------------------------------

2019:

Colunas padrão: ['TIMESTAMP', 'RECORD', 'BattV_Avg', 'Tar_AVG', 'UR_inst', 'Vvento_ms_AVG', 'Dvento_G', 'Qg_AVG', 'PAR_AVG', 'Rn_Avg', 'Chuva', 'Patm_kPa_AVG', 'rQg_AVG', 'Qatm_AVG', 'Qsup_AVG', 'Boc_AVG', 'Bol_AVG', 'Albedo_Avg', 'QatmC_AVG', 'QsupC_AVG', 'Vvento_ms_S_WVT', 'Dvento_D1_WVT', 'Dvento_SD1_WVT', 'PainelT', nan]
Colunas não nulas: ['TIMESTAMP', 'RECORD', 'BattV_Avg', 'Tar_AVG', 'UR_inst', 'Vvento_ms_AVG', 'Dvento_G', 'Qg_AVG', 'PAR_AVG', 'Rn_Avg', 'Chuva', 'Patm_kPa_AVG', 'rQg_AVG', 'Qatm_AVG', 'Qsup_AVG', 'Boc_AVG', 'Bol_AVG', 'Albedo_Avg', 'QatmC_AVG', 'QsupC_AVG', 'Vvento_ms_S_WVT', 'Dvento_D1_WVT', 'Dvento_SD1_WVT', 'PainelT']
Resultado: Valor nulo detectado após limpeza em ['RECORD']
Registros após remoções: 34008 linhas

---------------------------------------------------------------

2020:

Colunas padrão: ['TIMESTAMP', 'RECORD', 'BattV_Avg', 'Tar_AVG', 'UR_inst', 'Vvento_ms_AVG', 'Dvento_G', 'Qg_AVG', 'PAR_AVG', 'Rn_Avg', 'Chuva', 'Patm_kPa_AVG', 'rQg_AVG', 'Qatm_AVG', 'Qsup_AVG', 'Boc_AVG', 'Bol_AVG', 'Albedo_Avg', 'QatmC_AVG', 'QsupC_AVG', 'Vvento_ms_S_WVT', 'Dvento_D1_WVT', 'Dvento_SD1_WVT', 'PainelT']
Colunas não nulas: ['TIMESTAMP', 'RECORD', 'BattV_Avg', 'Tar_AVG', 'UR_inst', 'Vvento_ms_AVG', 'Dvento_G', 'Qg_AVG', 'PAR_AVG', 'Rn_Avg', 'Chuva', 'Patm_kPa_AVG', 'rQg_AVG', 'Qatm_AVG', 'Qsup_AVG', 'Boc_AVG', 'Bol_AVG', 'Albedo_Avg', 'QatmC_AVG', 'QsupC_AVG', 'Vvento_ms_S_WVT', 'Dvento_D1_WVT', 'Dvento_SD1_WVT', 'PainelT']
Resultado: OK

---------------------------------------------------------------

2021:

Colunas padrão: ['TIMESTAMP', 'RECORD', 'BattV_Avg', 'Tar_AVG', 'UR_inst', 'Vvento_ms_AVG', 'Dvento_G', 'Qg_AVG', 'PAR_AVG', 'Rn_Avg', 'Chuva', 'Patm_kPa_AVG', 'rQg_AVG', 'Qatm_AVG', 'Qsup_AVG', 'Boc_AVG', 'Bol_AVG', 'Albedo_Avg', 'QatmC_AVG', 'QsupC_AVG', 'Vvento_ms_S_WVT', 'Dvento_D1_WVT', 'Dvento_SD1_WVT', 'PainelT']
Colunas não nulas: ['TIMESTAMP', 'RECORD', 'BattV_Avg', 'Tar_AVG', 'UR_inst', 'Vvento_ms_AVG', 'Dvento_G', 'Qg_AVG', 'PAR_AVG', 'Rn_Avg', 'Chuva', 'Patm_kPa_AVG', 'rQg_AVG', 'Qatm_AVG', 'Qsup_AVG', 'Boc_AVG', 'Bol_AVG', 'Albedo_Avg', 'QatmC_AVG', 'QsupC_AVG', 'Vvento_ms_S_WVT', 'Dvento_D1_WVT', 'Dvento_SD1_WVT', 'PainelT']
Resultado: OK

---------------------------------------------------------------

A coluna __F.C.S.__ é pouco usada e não poderá ser utilizada para o modelo.